version: '4.28.0'

services:
  mongo-db:
    image: mongo:8.0-rc
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017